[general]
enable_bucket = true                        # Whether to use Aspect Ratio Bucketing

[[datasets]]
resolution = 512                            # Training resolution
batch_size = 2                              # Batch size

  [[datasets.subsets]]
  image_dir = './images'  
  class_tokens = 'sometoken woman'
  num_repeats = 30 

  [[datasets.subsets]]
  is_reg = true
  image_dir = '../reg_images'          # Specify the folder containing the regularization images
  class_tokens = 'woman'                     # Specify the class
  num_repeats = 1